async function main() {
}

main().catch((error) => {
    console.error("An error occurred:", error);
    process.exit(1);
});
